In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [7]:
## your code
deg = np.arange(1, 21, 1)
twos = np.ones(20)*2
vec = (twos**deg)/deg
print(vec)

[  2.00000000e+00   2.00000000e+00   2.66666667e+00   4.00000000e+00
   6.40000000e+00   1.06666667e+01   1.82857143e+01   3.20000000e+01
   5.68888889e+01   1.02400000e+02   1.86181818e+02   3.41333333e+02
   6.30153846e+02   1.17028571e+03   2.18453333e+03   4.09600000e+03
   7.71011765e+03   1.45635556e+04   2.75941053e+04   5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [6]:
## your code
i = np.arange(0, 6, 1)
fst = np.ones(6)*0.1
snd = np.ones(6)*0.2
forsum = (fst**(3*i))*(snd**(4*i))
print(forsum.sum())

1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [122]:
## your code
zrs=np.zeros((8, 8)) #создал нулевую матрицу 8х8
ons=np.ones(64).reshape(8, 8)
mat=np.arange(1,65).reshape(8, 8)

i = np.arange(0, 8).reshape(8, 1)
chessones=((mat+ons*i)%2) #создал матрицу с нулями и единицами в шахматном порядке

print(zrs+chessones) #заполнил нулевую матрицу "единицами в шахматном порядке"



[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [9]:
X = np.random.random((5, 2))

## your code
print('Декартовы:\n',X)
r=((X[:,0])**2+(X[:,1])**2)**(0.5)
phi=np.arctan2((X[:,0]),(X[:,1]))
polar=np.column_stack((r, phi))
print('Полярные:\n',polar)

Декартовы:
 [[ 0.89689533  0.50508138]
 [ 0.36757036  0.82753567]
 [ 0.56456398  0.28741753]
 [ 0.24039754  0.40097836]
 [ 0.67456775  0.31384167]]
Полярные:
 [[ 1.02933397  1.05791766]
 [ 0.90549613  0.41799901]
 [ 0.63351505  1.09989805]
 [ 0.46751965  0.54007197]
 [ 0.74400151  1.13533431]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [16]:
X = np.random.random((10, 10))

## your code
print(X)
ind=np.argmax(X)
print('(',(ind//10)+1,'строка,',(ind%10)+1,'элемент) (Индексация производится с единицы)')

[[ 0.89809903  0.4669317   0.69232921  0.94008656  0.65235059  0.53152328
   0.94803237  0.13014097  0.89954666  0.08186956]
 [ 0.07234164  0.3506625   0.94667028  0.67498919  0.4141433   0.06586614
   0.10340034  0.28076857  0.97380216  0.4237926 ]
 [ 0.16681572  0.00449683  0.66290951  0.16239053  0.39667242  0.35929931
   0.20495613  0.02993383  0.53906417  0.76962457]
 [ 0.17945615  0.07437351  0.0196415   0.57567386  0.62539299  0.24425841
   0.19514087  0.73817713  0.7122989   0.91993277]
 [ 0.20552958  0.54472039  0.37489165  0.89446414  0.7365081   0.50186273
   0.60359997  0.17502023  0.21303024  0.63448197]
 [ 0.28227399  0.64007709  0.98289018  0.16313033  0.32889658  0.67198545
   0.12082235  0.08887806  0.76036     0.40328687]
 [ 0.92879422  0.95516248  0.50550211  0.26937337  0.23828046  0.65942254
   0.89733578  0.78223318  0.37370791  0.95681617]
 [ 0.91693804  0.74457311  0.06020781  0.95229171  0.39358786  0.53761967
   0.41517633  0.90256536  0.1663044   0.26705743]


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [109]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
dist=((((X[:,0]-X[:,1])**2)+((y[0,0]-y[0,1])**2))**(0.5))
m=np.argmin(dist)
print(X[m])

[ 0.56942362  0.71485435]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [163]:
## your code
@np.vectorize
def f(x):
    if x<0:
        return x**2 + 2*x + 6
    if x>=0 and x<=2:
        return x + 6
    if x>2:
        return x**2 + 4*x - 4
    

m=np.arange(-3, 4, 0.1)
mas=f(m)
print(mas)

[  9.     8.61   8.24   7.89   7.56   7.25   6.96   6.69   6.44   6.21   6.
   5.81   5.64   5.49   5.36   5.25   5.16   5.09   5.04   5.01   5.     5.01
   5.04   5.09   5.16   5.25   5.36   5.49   5.64   5.81   6.     6.1    6.2
   6.3    6.4    6.5    6.6    6.7    6.8    6.9    7.     7.1    7.2    7.3
   7.4    7.5    7.6    7.7    7.8    7.9    8.     8.81   9.64  10.49
  11.36  12.25  13.16  14.09  15.04  16.01  17.    18.01  19.04  20.09
  21.16  22.25  23.36  24.49  25.64  26.81]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [142]:
X = np.random.random((10, 10))

## your code
m=np.mean(X, axis=1).reshape(10,1)
NX=X-m
nm=np.mean(NX, axis=1).reshape(10,1)
print(nm) #погрешности округлений, наверное

[[ -6.66133815e-17]
 [ -4.44089210e-17]
 [  1.22124533e-16]
 [  5.55111512e-17]
 [  0.00000000e+00]
 [  1.11022302e-17]
 [  0.00000000e+00]
 [  5.55111512e-17]
 [  3.33066907e-17]
 [ -4.44089210e-17]]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [145]:
X = np.random.normal(loc=5, scale=2., size=1000)

sred = np.sum(X)/np.size(X)
disp = (np.sum((X-sred)**2))/np.size(X)
print(sred, disp)

4.99389292312 4.01125132136


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [118]:
## your code
mat=np.arange(0,25).reshape(5, 5)
i = np.arange(0, 5).reshape(5, 1)
ons = np.ones(25).reshape(5, 5)
print((mat+ons*i)%5)

[[ 0.  1.  2.  3.  4.]
 [ 1.  2.  3.  4.  0.]
 [ 2.  3.  4.  0.  1.]
 [ 3.  4.  0.  1.  2.]
 [ 4.  0.  1.  2.  3.]]
